<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PublishTrimmed Condition="'$(Configuration)' == 'Release'">true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildProjectDirectory)/../VERSION').Trim())</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/sothis.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/sothis-portrait.png" />
    <EmbeddedResource Include="Localization/*.json" WithCulture="false" />
    <ProjectReference Include="../core/Core.csproj" />
    <PackageReference Include="Avalonia" Version="12.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageReference Include="SukiUI" Version="7.0.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.3" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition="'$(PublishTrimmed)' == 'true'">
    <ProjectReference Include="../cli/Cli.csproj" />
    <TrimmerRootAssembly Include="FethEditor.Gui" />
    <TrimmerRootAssembly Include="FethEditor.Core" />
    <TrimmerRootAssembly Include="FethEditor.Cli" />
  </ItemGroup>
  <PropertyGroup Condition="'$(PublishTrimmed)' == 'true'">
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
</Project>
