<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>FETH_Cli</AssemblyName>
    <LangVersion>latest</LangVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Core/SaveBuffer.cs" Link="SaveBuffer.cs" />
    <Compile Include="../Core/NgPlusJournal.cs" Link="NgPlusJournal.cs" />
    <Reference Include="System.Web.Extensions" />
    <ProjectReference Include="../SaveEditor/SaveEditor.csproj" />
  </ItemGroup>
</Project>
